### ISSUE TITLE
Euphonic: ASE task breakdown

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Pace-Project-Plan#188]
Investigate and determine effort required to provide an interface to ASE

**Comment by ajjackson** [comment]
### Background

ASE has an established workflow for vibrations and phonons. In this context "Vibrations" models involve a harmonic Hessian of a system that may or may not be periodic. "Phonons" are similar but use a supercell and contain information about the supercell/primitive-cell relationship (and optionally born charge / dielectric information) to enable Fourier interpolation.

There have been some issues with these implementations:

- They use an object-oriented workflow in which a finite-displacement calculation is initialised, then run, then results are read, then properties are calculated. It can be fragile and awkward to serialise, restart and distribute calculations. It also doesn't permit force constant data from other sources to easily be loaded into the same analysis methods.
- The Phonons workflow is restricted to diagonal supercell matrices
- Some issues have been observed with the Fourier interpolation and handling of polar materials:
  - https://gitlab.com/ase/ase/-/issues/941
  - https://gitlab.com/ase/ase/-/merge_requests/2095
- No symmetry constraints are implemented
- A conservation rule is implemented in the Vibrations scheme as a parameter that is set initially and performed when reading in displacement data.

There has been quite a bit of discussion and progress on these matters.
- I have already refactored the Vibrations system so that there is now a standalone data container "VibrationsData" which can be initialised from existing data or serialised to JSON and is responsible for performing the analysis methods (e.g. calculating frequencies, writing animated displacements). This is roughly equivalent to a Euphonic ForceConstants object, but without the supercell and NAC complications.
- I have mostly completed work on some new tools for _performing_ finite-displacement vibration calculations https://gitlab.com/ase/ase/-/merge_requests/2576 . This addresses some of the practical issues with e.g. distributing large calculations on clusters, and hopefully will allow us to one day drop the old Vibrations class. However, there are still some Raman methods based on the existing Vibrations class and a successor approach to those would need to be implemented first.
- A natural next step from there will be to implement a new PhononData class. This would essentially be ASE's version of the Euphonic ForceConstants, and would
  - Implement some basic methods for accessing properties and Fourier interpolation. They don't have to be very fancy, as ...
  - ... it would also be possible to make use of Phonopy and/or Euphonic as an external library for more optimised interpolation and extra features.
  An ASE user did already make a start on this class but we found a few complications; I'm keen to avoid baking in limitations that might hinder interoperability with more sophisticated schemes. https://gitlab.com/ase/ase/-/merge_requests/2493

### Priorities

- I think it will be helpful to have a PhononData prototype working as soon as possible, even with a port of the existing (questionable) Fourier interpolation. Once it is easy to interchange with Phonopy and Euphonic it will be much easier to interrogate these interpolation schemes and figure out where they differ. This could mean that e.g. the native ASE implementation of methods is limited to diagonal supercells but external tools can handle more options.

- A useful stepping stone might also be a VibrationsData -> PhononData converter. Then we can use some existing (or emerging) conversions to VibrationsData and fold supercell calcultions to a primitive-referenced model model.

- With PhononData -> Euphonic in place we can wholeheartedly encourage creation of ASE PhononData readers for GULP, Espresso, hiphive etc without adding anything to Euphonic.

- We will need to work with code reviewers and get buy-in from other ASE contributors with an interest in phonon features.

### Sequencing

- Realistically I need to close out the finite displacement vibrations work first.

- We need an initial prototype of PhononData which is similar to VibrationsData

- Some interfaces to external data should be implemented while this is still in a development branch, as it will
  a) influence decisions about the nature and format of data that needs to be included, and
  b) give more confidence and understanding of behaviour compared with other codes.

- When the initial merge request is done, additional formats and features can be developed independently

### Risks/challenges
- Lately it can be a bit slow to get code reviews and releases for ASE
- We need to think carefully about what kind of Fourier interpolation and long-range corrections will be implemented. We don't want to repeat all the work done in other libraries already, but it makes sense for ASE to include a simple non-optimised reference implementation that sensibly uses the available data. This way ASE does not gain dependencies but e.g. Born charge data will be properly tested and reliably included.

**Comment by rebeccafair** [comment]
Closing as completed, specific tasks should be added to https://github.com/pace-neutrons/Pace-Project-Plan/issues/181
